### ISSUE TITLE
mysql login and Runtime error

### ISSUE THREAD

**Issue by kr1sti4n** [arikogan/mysql-gelf#1]
Hi, 

When I run the script I'm getting following output 

---

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
Runtime error (func=(main), adr=9): Divide by zero
/root/mysql-gelf-master

---

I tried  login details manually on shell and I was able to login just fine. 
Seems like the script is not passing the mysql login part for some reason. 
I tried with other mysql login formats from bash like --usernam and --password instead of -u and -p  but always end up with same result. 

Do you have any idea why this would happen ? I'm running centos  6.7 

thnx, 
Kristian

**Comment by arikogan** [comment]
Hi @kr1sti4n 
Can you maybe add a debugging echo in line 24? You can add

``` bash
echo $STATUS_CMD
```

and try the output on the command line. If same command works on the command line, what would be very weird. Thanks.

**Comment by kr1sti4n** [comment]
Doooh :(  ... I had $ in my mysql root password. So when the script would  execute it would read only password up to $ but not after it.  I forgot that in bash $ will be interpreted. 
But thank you for the hint that helped me to solve this out. :)

**Comment by arikogan** [comment]
I see, needs to be escaped then, I'm not aware of another way of doing it.
Thanks for pointing it out.
